name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Go test
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic -v
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
